/** @type {import('tailwindcss').Config} */
export const content = [
  '*.php',
  'templates/**/*.{php,twig}',
  './Components/**/*.{php,twig}',
  './Atoms/**/*.{php,twig}',
]
export const theme = {
  borderWidth: {
    DEFAULT: '2px',
    0: '0',
    1: '1px',
    2: '2px',
    3: '3px',
  },
  colors: {
    /** Colors (Primitives) */
    current: 'currentColor',
    transparent: 'transparent',
    /** Colors (Tokens) */
    textColor: 'var(--textColor)',
    bgColor: 'var(--bgColor)',
    brandColor: 'var(--brandColor)',
    accentColor: 'var(--accentColor)',
    hoverColor: 'var(--hoverColor)',
    activeColor: 'var(--bluepressed)',
    borderColor: 'var(--borderColor)',
    uiColor: 'var(--uiColor)',
  },
  fontSize: {
    bodyMobile: ['1rem', '1.5'],
    body: ['1.125rem', '1.4444'],
    bodyWide: ['1.25rem', '1.4'],
    buttonMobile: ['0.875rem', '1.25rem'],
    button: ['1rem', '1.5'],
    buttonWide: ['1.125rem', '1.625rem'],
    // --
    titleLarge: ['4.813rem', 'normal'],
    titleLargeMobile: ['2.813rem', 'normal'],
    titleSmall: ['3.438rem', '110%'],
    titleSmallMobile: ['2.188rem', 'normal'],
    subtitle: ['2.188rem', 'normal'],
    subtitleMobile: ['1.875rem', 'normal'],
    // button: ['1.25rem', 'normal'],
    buttonSmall: ['1.125rem', 'normal'],
    glance: ['2.813rem', '110%'],
    glanceMobile: ['1.5rem', '110%'],
    caption: ['1.125rem', 'normal'],
    captionMobile: ['0.938rem', 'normal'],
  },
  screens: {
    xs: '640px',
    sm: '780px',
    md: '980px',
    lg: '1080px',
    xl: '1280px',
    xxl: '1440px',
    wide: '1600px',
    max: '1880px',
  },
  container: {
    padding: {
      DEFAULT: '20px',
      sm: '60px',
    },
  },
  extend: {
    aspectRatio: {
      '4/3': '4 / 3',
      '3/4': '3 / 4',
      '2/1': '2 / 1',
    },
    borderWidth: {
      DEFAULT: '2px',
      0: '0',
      1: '1px',
      2: '2px',
      3: '3px',
      4: '4px',
    },
    brightness: {
      70: '.70',
    },
    fontFamily: {
      mono: ['Aeonik Mono'],
    },
    height: {
      xs: '10px',
      sm: '15px',
      md: '35px',
      lg: '50px',
      xl: '75px',
      xxl: '125px',
      max: '200px',
    },
    spacing: {
      xs: '10px',
      sm: '20px',
      md: '40px',
      lg: '60px',
      xl: '80px',
      xxl: '120px',
      max: '200px',
    },
  },
}
export const purge = {
  safelist: ['w-1/2', 'translate-x-full', '!translate-x-0'],
}

export const plugins = []

export const safelist = [
  'col-span-1',
  'col-span-2',
  'col-span-3',
  'col-span-4',
  'col-span-5',
  'col-span-6',
  'col-span-7',
  'col-span-8',
  'col-span-9',
  'col-span-10',
  'col-span-11',
  'xs:col-span-12',
  'xs:col-span-1',
  'xs:col-span-2',
  'xs:col-span-3',
  'xs:col-span-4',
  'xs:col-span-5',
  'xs:col-span-6',
  'xs:col-span-7',
  'xs:col-span-8',
  'xs:col-span-9',
  'xs:col-span-10',
  'xs:col-span-11',
  'xs:col-span-12',
  'sm:col-span-1',
  'sm:col-span-2',
  'sm:col-span-3',
  'sm:col-span-4',
  'sm:col-span-5',
  'sm:col-span-6',
  'sm:col-span-7',
  'sm:col-span-8',
  'sm:col-span-9',
  'sm:col-span-10',
  'sm:col-span-11',
  'sm:col-span-12',
  'md:col-span-1',
  'md:col-span-2',
  'md:col-span-3',
  'md:col-span-4',
  'md:col-span-5',
  'md:col-span-6',
  'md:col-span-7',
  'md:col-span-8',
  'md:col-span-9',
  'md:col-span-10',
  'md:col-span-11',
  'lg:col-span-12',
  'lg:col-span-1',
  'lg:col-span-2',
  'lg:col-span-3',
  'lg:col-span-4',
  'lg:col-span-5',
  'lg:col-span-6',
  'lg:col-span-7',
  'lg:col-span-8',
  'lg:col-span-9',
  'lg:col-span-10',
  'lg:col-span-11',
  'lg:col-span-12',
  'xl:col-span-1',
  'xl:col-span-2',
  'xl:col-span-3',
  'xl:col-span-4',
  'xl:col-span-5',
  'xl:col-span-6',
  'xl:col-span-7',
  'xl:col-span-8',
  'xl:col-span-9',
  'xl:col-span-10',
  'xl:col-span-11',
  'xl:col-span-12',
  'xxl:col-span-1',
  'xxl:col-span-2',
  'xxl:col-span-3',
  'xxl:col-span-4',
  'xxl:col-span-5',
  'xxl:col-span-6',
  'xxl:col-span-7',
  'xxl:col-span-8',
  'xxl:col-span-9',
  'xxl:col-span-10',
  'xxl:col-span-11',
  'xxl:col-span-12',
  'wide:col-span-1',
  'wide:col-span-2',
  'wide:col-span-3',
  'wide:col-span-4',
  'wide:col-span-5',
  'wide:col-span-6',
  'wide:col-span-7',
  'wide:col-span-8',
  'wide:col-span-9',
  'wide:col-span-10',
  'wide:col-span-11',
  'wide:col-span-12',
]

export const darkMode = 'class'
