<?php

namespace Flynt\Components\DonationForm;

use Flynt\Utils\Options;

/**
 * Provides the ACF (Advanced Custom Fields) layout definition for the
 * DonationForm component.
 *
 * This layout is used to configure donation forms via the WordPress backend.
 * It defines fields for the FundraisingBox form hash, donation intervals,
 * and specific donation amount options per interval.
 *
 * @return array
 *   The ACF layout definition array for the DonationForm component.
 */
function getACFLayout(): array {
  return [
    'name' => 'DonationForm',
    'label' => 'Donation Form',
    'sub_fields' => [
      // --- Formular Auswahl ---
      [
        'label' => __('Bitte das Formular auswählen (je Sprache)', 'flynt'),
        'name' => 'hash',
        'type' => 'select',
        'choices' => [
          '0rtnskztep1awzb6' => 'Formular Deutsch',
          '4jppw6zr4ckbxmfl' => 'Formular English',
          'b8x47ctvkjzseldm' => 'Formular Italian',
          '24n2n3xvergvocld' => 'Formular Meta 1 DE',
          'n42zax2yu8ticpnv' => 'Formular Meta 2 DE',
        ],
        'required' => 1,
        'ui' => 1,
        'return_format' => 'value',
      ],
      [
        'label' => __('Formular hash (optional, überschreibt die Dropdown-Auswahl)', 'flynt'),
        'name' => 'form_hash',
        'type' => 'text',
        'instructions' => __('Trage hier einen spezifischen Formular-Hash ein, um die Auswahl oben zu überschreiben. Wird kein Wert eingegeben, wird die Dropdown-Auswahl verwendet.', 'flynt'),
        'required' => 0,
      ],

      // --- Aktive Intervalle (Checkbox) ---
      [
        'label' => __('Aktive Intervalle', 'flynt'),
        'name' => 'active_intervals',
        'type' => 'checkbox',
        'choices' => [
          '0' => __('einmalig', 'flynt'),
          '12' => __('jährlich', 'flynt'),
          '6' => __('halbjährlich', 'flynt'),
          '3' => __('vierteljährlich', 'flynt'),
          '1' => __('monatlich', 'flynt'),
        ],
        'default_value' => ['0', '1'],
        'layout' => 'horizontal',
        'instructions' => __('Wähle aus, welche Intervalle im Formular angezeigt werden sollen. (min 1 - max 3)', 'flynt'),
      ],
      [
        'label' => __('Intervall', 'flynt'),
        'instructions' => __('Wähle das Intervall aus welches zuerst angezeigt werden soll. Beachte, das es eins aus Aktiven Intervallen ausgewählt sein muss.', 'flynt'),
        'name' => 'interval',
        'type' => 'radio',
        'choices' => [
          '0' => __('einmalig', 'flynt'),
          '12' => __('jährlich', 'flynt'),
          '6' => __('halbjährlich', 'flynt'),
          '3' => __('vierteljährlich', 'flynt'),
          '1' => __('monatlich', 'flynt'),
        ],
        'required' => 1,
        'default_value' => '0',
        'layout' => 'horizontal',
      ],
      [
        'label' => __('Titel Intervall Panel (Meine Spende)', 'flynt'),
        'name' => 'field_label_interval_panel',
        'type' => 'text',
        'instructions' => __('Bitte anpassen, wenn nur ein Intervall ausgewählt ist (Beispiel: Meine monatliche Spende, wenn nur monatlich ausgewählt). Wenn nicht ausgefüllt, wird der Titel "Meine Spende" angezeigt.', 'flynt'),
        'required' => 0,
      ],
      [
        'label' => __('Leave No One Behind Newsletter Checkbox anzeigen', 'flynt'),
        'name' => 'show_no_leave_behind',
        'type' => 'true_false',
        'ui' => 1,
        'default_value' => 0,
        'required' => 0,
      ],
      [
        'label' => __('Mindestspendenbetrag', 'flynt'),
        'name' => 'minAmount',
        'type' => 'number',
        'instructions' => __('Trage hier den Mindestbetrag ein. Bitte mit der Fundraisingbox abgleichen.', 'flynt'),
        'required' => 1,
        'step' => 1,
        'min' => 1,
        'default_value' => 3,
      ],
      [
        'label' => __('Maximalspendenbetrag', 'flynt'),
        'name' => 'maxAmount',
        'type' => 'number',
        'instructions' => __('Trage hier den Maximalbetrag ein. Bitte mit der Fundraisingbox abgleichen.', 'flynt'),
        'required' => 1,
        'step' => 1,
        'min' => 1,
        'default_value' => 10000,
      ],
      [
        'label' => __('Eigenen Betrag anzeigen', 'flynt'),
        'name' => 'show_custom_amount',
        'type' => 'true_false',
        'ui' => 1,
        'default_value' => 1,
        'instructions' => __('Wenn deaktiviert, wird das Feld für den eigenen Betrag nicht angezeigt.', 'flynt'),
      ],
      // --- Betrags-Repeater pro Intervall ---
      // Einmalig
      [
        'label' => __('Betragsvorschläge einmalig', 'flynt'),
        'name' => 'amounts_one_time',
        'type' => 'repeater',
        'min' => 3,
        'max' => 4,
        'button_label' => __('Add Amount Option', 'flynt'),
        'conditional_logic' => [
          [
            [
              'field' => 'field_pageComponents_pageComponents_DonationForm_active_intervals',
              'operator' => '==',
              'value' => '0',
            ],
          ],
        ],
        'sub_fields' => [
          [
            'label' => __('Betrag', 'flynt'),
            'name' => 'value',
            'type' => 'number',
            'min' => 5,
            'default_value' => 10,
            'required' => 1,
          ],
          [
            'label' => __('Standard Betrag', 'flynt'),
            'name' => 'default',
            'type' => 'true_false',
            'ui' => 1,
          ],
        ],
      ],

      // Jährlich
      [
        'label' => __('Betragsvorschläge jährlich', 'flynt'),
        'name' => 'amounts_yearly',
        'type' => 'repeater',
        'min' => 3,
        'max' => 4,
        'button_label' => __('Add Amount Option', 'flynt'),
        'conditional_logic' => [
          [
            [
              'field' => 'field_pageComponents_pageComponents_DonationForm_active_intervals',
              'operator' => '==',
              'value' => '12',
            ],
          ],
        ],
        'sub_fields' => [
          [
            'label' => __('Betrag', 'flynt'),
            'name' => 'value',
            'type' => 'number',
            'min' => 5,
            'default_value' => 10,
            'required' => 1,
          ],
          [
            'label' => __('Standard Betrag', 'flynt'),
            'name' => 'default',
            'type' => 'true_false',
            'ui' => 1,
          ],
        ],
      ],

      // Halbjährlich
      [
        'label' => __('Betragsvorschläge halbjährlich', 'flynt'),
        'name' => 'amounts_half_yearly',
        'type' => 'repeater',
        'min' => 3,
        'max' => 4,
        'button_label' => __('Add Amount Option', 'flynt'),
        'conditional_logic' => [
          [
            [
              'field' => 'field_pageComponents_pageComponents_DonationForm_active_intervals',
              'operator' => '==',
              'value' => '6',
            ],
          ],
        ],
        'sub_fields' => [
          [
            'label' => __('Betrag', 'flynt'),
            'name' => 'value',
            'type' => 'number',
            'min' => 5,
            'default_value' => 10,
            'required' => 1,
          ],
          [
            'label' => __('Standard Betrag', 'flynt'),
            'name' => 'default',
            'type' => 'true_false',
            'ui' => 1,
          ],
        ],
      ],

      // Vierteljährlich
      [
        'label' => __('Betragsvorschläge vierteljährlich', 'flynt'),
        'name' => 'amounts_quarterly',
        'type' => 'repeater',
        'min' => 3,
        'max' => 4,
        'button_label' => __('Add Amount Option', 'flynt'),
        'conditional_logic' => [
          [
            [
              'field' => 'field_pageComponents_pageComponents_DonationForm_active_intervals',
              'operator' => '==',
              'value' => '3',
            ],
          ],
        ],
        'sub_fields' => [
          [
            'label' => __('Betrag', 'flynt'),
            'name' => 'value',
            'type' => 'number',
            'min' => 5,
            'default_value' => 10,
            'required' => 1,
          ],
          [
            'label' => __('Standard Betrag', 'flynt'),
            'name' => 'default',
            'type' => 'true_false',
            'ui' => 1,
          ],
        ],
      ],

      // Monatlich
      [
        'label' => __('Betragsvorschläge monatlich', 'flynt'),
        'name' => 'amounts_monthly',
        'type' => 'repeater',
        'min' => 3,
        'max' => 4,
        'button_label' => __('Add Amount Option', 'flynt'),
        'conditional_logic' => [
          [
            [
              'field' => 'field_pageComponents_pageComponents_DonationForm_active_intervals',
              'operator' => '==',
              'value' => '1',
            ],
          ],
        ],
        'sub_fields' => [
          [
            'label' => __('Betrag', 'flynt'),
            'name' => 'value',
            'type' => 'number',
            'min' => 5,
            'default_value' => 10,
            'required' => 1,
          ],
          [
            'label' => __('Standard Betrag', 'flynt'),
            'name' => 'default',
            'type' => 'true_false',
            'ui' => 1,
          ],
        ],
      ],

      // --- Nudge Text & Anzeigen ---
      [
        'label' => __('Nudge Text', 'flynt'),
        'name' => 'nudge_text',
        'type' => 'wysiwyg',
        'toolbar' => 'basic',
        'tabs' => 'visual',
        'media_upload' => 0,
        'required' => 0,
      ],
      [
        'label' => __('Nudge Text anzeigen', 'flynt'),
        'name' => 'show_nudge_text',
        'type' => 'true_false',
        'ui' => 1,
        'default_value' => 0,
        'required' => 0,
      ],
      [
        'label' => __('Wertversprechen', 'flynt'),
        'name' => 'value_proposition',
        'type' => 'wysiwyg',
        'tabs' => 'visual',
        'media_upload' => 0,
        'required' => 0,
      ],
      [
        'label' => __('Wertversprechen anzeigen', 'flynt'),
        'name' => 'show_value_proposition',
        'type' => 'true_false',
        'ui' => 1,
        'default_value' => 0,
        'required' => 0,
      ],
      [
        'label' => __('Hinweis sicheres Spenden', 'flynt'),
        'name' => 'security_notice',
        'type' => 'wysiwyg',
        'toolbar' => 'basic',
        'tabs' => 'visual',
        'media_upload' => 0,
        'required' => 1,
      ],
      [
        'label' => __('Datenschutz Hinweis', 'flynt'),
        'name' => 'privacy_notice',
        'type' => 'wysiwyg',
        'toolbar' => 'basic',
        'tabs' => 'visual',
        'media_upload' => 0,
        'required' => 1,
      ],
      [
        'label' => __('Danke-Seite Einmalspende', 'flynt'),
        'name' => 'thx_one_time',
        'type' => 'link',
        'required' => 1,
      ],
      [
        'label' => __('Danke-Seite Dauerspende', 'flynt'),
        'name' => 'thx_recurring',
        'type' => 'link',
        'required' => 1,
      ],
      [
        'label' => __('Eingebettete Komponenten', 'flynt'),
        'name' => 'nested_components',
        'type' => 'flexible_content',
        'button_label' => __('Komponente hinzufügen', 'flynt'),
        'layouts' => [
          [
            'name' => 'DonationBarometer',
            'label' => 'Donation Barometer',
            'sub_fields' => \Flynt\Components\DonationBarometer\getACFLayout()['sub_fields'],
          ],
        ],
      ],
    ],
  ];
}

Options::addTranslatable('DonationForm', [
  [
    'label' => __('Allgemeine Einstellungen', 'flynt'),
    'name' => 'labelsTab',
    'type' => 'tab',
    'placement' => 'top',
    'endpoint' => 0,
  ],
  [
    'label' => __('Text für Spendenbutton (Standard)', 'flynt'),
    'name' => 'submitButtonTextDefault',
    'type' => 'text',
    'instructions' => __('Text für den allgemeinen Spendenbutton, z. B. „Jetzt Spenden“.', 'flynt'),
    'default_value' => __('Jetzt Spenden', 'flynt'),
    'wrapper' => ['width' => 50],
  ],
  [
    'label' => __('Text für Spendenbutton (Einmalige Spende)', 'flynt'),
    'name' => 'submitButtonTextOneTime',
    'type' => 'text',
    'instructions' => __('Text für einmalige Spende, „%amount%“ wird durch den Betrag ersetzt, z. B. „Einmalig 50 Euro spenden“.', 'flynt'),
    'default_value' => __('Einmalig %amount% Euro spenden', 'flynt'),
    'wrapper' => ['width' => 50],
  ],
  [
    'label' => __('Text für Spendenbutton (Jährliche Spende)', 'flynt'),
    'name' => 'submitButtonTextYearly',
    'type' => 'text',
    'instructions' => __('Text für jährliche Spende, „%amount%“ wird durch den Betrag ersetzt, z. B. „Jährlich 50 Euro spenden“.', 'flynt'),
    'default_value' => __('Jährlich %amount% Euro spenden', 'flynt'),
    'wrapper' => ['width' => 50],
  ],
  [
    'label' => __('Text für Spendenbutton (Halbjährliche Spende)', 'flynt'),
    'name' => 'submitButtonTextHalfYearly',
    'type' => 'text',
    'instructions' => __('Text für halbjährliche Spende, „%amount%“ wird durch den Betrag ersetzt, z. B. „Halbjährlich 50 Euro spenden“.', 'flynt'),
    'default_value' => __('Halbjährlich %amount% Euro spenden', 'flynt'),
    'wrapper' => ['width' => 50],
  ],
  [
    'label' => __('Text für Spendenbutton (Vierteljährliche Spende)', 'flynt'),
    'name' => 'submitButtonTextQuarterly',
    'type' => 'text',
    'instructions' => __('Text für vierteljährliche Spende, „%amount%“ wird durch den Betrag ersetzt, z. B. „Vierteljährlich 50 Euro spenden“.', 'flynt'),
    'default_value' => __('Vierteljährlich %amount% Euro spenden', 'flynt'),
    'wrapper' => ['width' => 50],
  ],
  [
    'label' => __('Text für Spendenbutton (Monatliche Spende)', 'flynt'),
    'name' => 'submitButtonTextMonthly',
    'type' => 'text',
    'instructions' => __('Text für monatliche Spende, „%amount%“ wird durch den Betrag ersetzt, z. B. „Monatlich 20 Euro spenden“.', 'flynt'),
    'default_value' => __('Monatlich %amount% Euro spenden', 'flynt'),
    'wrapper' => ['width' => 50],
  ],
  [
    'label' => __('Formularfelder', 'flynt'),
    'name' => 'formLabelsTab',
    'type' => 'tab',
    'placement' => 'top',
    'endpoint' => 0,
  ],
  [
    'label' => __('Titel für Spendenintervall-Abschnitt', 'flynt'),
    'name' => 'labelPanelInterval',
    'type' => 'text',
    'instructions' => __('Überschrift für den Abschnitt zur Auswahl von Einmalig/Monatlich, z. B. „Meine Spende“.', 'flynt'),
    'default_value' => __('Meine Spende', 'flynt'),
    'wrapper' => ['width' => 100],
  ],
  [
    'label' => __('Text für Intervall „Einmalig“', 'flynt'),
    'name' => 'oneTimeIntervalText',
    'type' => 'text',
    'instructions' => __('Text für die Option „Einmalige Spende“ im Formular, z. B. „Einmalig“.', 'flynt'),
    'default_value' => __('Einmalig', 'flynt'),
    'wrapper' => ['width' => 50],
  ],
  [
    'label' => __('Text für Intervall „Monatlich“', 'flynt'),
    'name' => 'monthlyIntervalText',
    'type' => 'text',
    'instructions' => __('Text für die Option „Monatliche Spende“ im Formular, z. B. „Monatlich“.', 'flynt'),
    'default_value' => __('Monatlich', 'flynt'),
    'wrapper' => ['width' => 50],
  ],
  [
    'label' => __('Text für Intervall „Vierteljährlich“', 'flynt'),
    'name' => 'quarterlyIntervalText',
    'type' => 'text',
    'instructions' => __('Text für die Option „Vierteljährliche Spende“ im Formular, z. B. „Vierteljährlich“.', 'flynt'),
    'default_value' => __('Vierteljährlich', 'flynt'),
    'wrapper' => ['width' => 50],
  ],
  [
    'label' => __('Text für Intervall „Halbjährlich“', 'flynt'),
    'name' => 'halfYearlyIntervalText',
    'type' => 'text',
    'instructions' => __('Text für die Option „Halbjährliche Spende“ im Formular, z. B. „Halbjährlich“.', 'flynt'),
    'default_value' => __('Halbjährlich', 'flynt'),
    'wrapper' => ['width' => 50],
  ],
  [
    'label' => __('Text für Intervall „Jährlich“', 'flynt'),
    'name' => 'yearlyIntervalText',
    'type' => 'text',
    'instructions' => __('Text für die Option „Jährliche Spende“ im Formular, z. B. „Jährlich“.', 'flynt'),
    'default_value' => __('Jährlich', 'flynt'),
    'wrapper' => ['width' => 50],
  ],
  [
    'label' => __('Platzhalter für eigenes Betragsfeld', 'flynt'),
    'name' => 'customAmountPlaceholder',
    'type' => 'text',
    'instructions' => __('Hinweistext im Feld für einen benutzerdefinierten Spendenbetrag, z. B. „Eigener Betrag“.', 'flynt'),
    'default_value' => __('Eigener Betrag', 'flynt'),
    'wrapper' => ['width' => 50],
  ],
  [
    'label' => __('Titel für Kontaktdaten-Abschnitt', 'flynt'),
    'name' => 'labelContactPanel',
    'type' => 'text',
    'instructions' => __('Überschrift für den Abschnitt mit den Kontaktdaten, z. B. „Meine Kontaktdaten“.', 'flynt'),
    'default_value' => __('Meine Kontaktdaten', 'flynt'),
    'wrapper' => ['width' => 100],
  ],
  [
    'label' => __('Feld für Select Box mobil', 'flynt'),
    'name' => 'labelSalutationSelectBox',
    'type' => 'text',
    'instructions' => __('Label für das Select Box Drop Down, z. B. „Anrede“.', 'flynt'),
    'default_value' => __('Anrede', 'flynt'),
    'wrapper' => ['width' => 50],
  ],
  [
    'label' => __('Anrede Select Box leere Option „Anrede wählen“', 'flynt'),
    'name' => 'salutationSelectEmptyOption',
    'type' => 'text',
    'instructions' => __('Text für die Anrede der Select Box leere Option „Anrede wählen“ im Formular. Wird nur mobil angezeigt.', 'flynt'),
    'default_value' => __('Anrede wählen', 'flynt'),
    'wrapper' => ['width' => 50],
  ],
  [
    'label' => __('Anrede „Frau“', 'flynt'),
    'name' => 'salutationMrs',
    'type' => 'text',
    'instructions' => __('Text für die Anrede „Frau“ im Formular.', 'flynt'),
    'default_value' => __('Frau', 'flynt'),
    'wrapper' => ['width' => 33],
  ],
  [
    'label' => __('Anrede „Herr“', 'flynt'),
    'name' => 'salutationMr',
    'type' => 'text',
    'instructions' => __('Text für die Anrede „Herr“ im Formular.', 'flynt'),
    'default_value' => __('Herr', 'flynt'),
    'wrapper' => ['width' => 33],
  ],
  [
    'label' => __('Anrede „Divers“', 'flynt'),
    'name' => 'salutationDivers',
    'type' => 'text',
    'instructions' => __('Text für die neutrale Anrede im Formular, z. B. „Ohne Angabe“.', 'flynt'),
    'default_value' => __('Ohne Angabe', 'flynt'),
    'wrapper' => ['width' => 33],
  ],
  [
    'label' => __('Feld für Vorname', 'flynt'),
    'name' => 'firstNameLabel',
    'type' => 'text',
    'instructions' => __('Label für das Vornamenfeld, z. B. „Vorname“.', 'flynt'),
    'default_value' => __('Vorname', 'flynt'),
    'wrapper' => ['width' => 50],
  ],
  [
    'label' => __('Feld für Nachname', 'flynt'),
    'name' => 'lastNameLabel',
    'type' => 'text',
    'instructions' => __('Label für das Nachnamenfeld, z. B. „Nachname“.', 'flynt'),
    'default_value' => __('Nachname', 'flynt'),
    'wrapper' => ['width' => 50],
  ],
  [
    'label' => __('Feld für E-Mail-Adresse', 'flynt'),
    'name' => 'emailAddressLabel',
    'type' => 'text',
    'instructions' => __('Label für das E-Mail-Feld, z. B. „E-Mail-Adresse“.', 'flynt'),
    'default_value' => __('E-Mail-Adresse', 'flynt'),
    'wrapper' => ['width' => 50],
  ],
  [
    'label' => __('Feld für Telefonnummer', 'flynt'),
    'name' => 'phoneLabel',
    'type' => 'text',
    'instructions' => __('Label für das Telefonnummernfeld, z. B. „Telefonnummer“.', 'flynt'),
    'default_value' => __('Telefonnummer', 'flynt'),
    'wrapper' => ['width' => 100],
  ],
  [
    'label' => __('Hinweis für Telefonnummer', 'flynt'),
    'name' => 'phoneNoticeText',
    'type' => 'wysiwyg',
    'toolbar' => 'basic',
    'media_upload' => 0,
    'instructions' => __('Hinweistext unter dem Telefonfeld, z. B. Zustimmung für Rückrufe.', 'flynt'),
    'default_value' => __('Gern erlaube ich SOS-Humanity mich ggf. anzurufen und mich über ihre Arbeit sowie Möglichkeiten der Unterstützung zu informieren. Diese Einwilligung kann ich jederzeit widerrufen.', 'flynt'),
    'wrapper' => ['width' => 100],
  ],
  [
    'label' => __('Option für Privatspende', 'flynt'),
    'name' => 'labelPrivateDonation',
    'type' => 'text',
    'instructions' => __('Text für die Option „Privatspende“, z. B. „Ich spende als Privatperson“.', 'flynt'),
    'default_value' => __('Ich spende als Privatperson', 'flynt'),
    'wrapper' => ['width' => 50],
  ],
  [
    'label' => __('Option für Unternehmensspende', 'flynt'),
    'name' => 'labelCompanyDonation',
    'type' => 'text',
    'instructions' => __('Text für die Option „Unternehmensspende“, z. B. „Ich möchte als Unternehmen spenden“.', 'flynt'),
    'default_value' => __('Ich möchte als Unternehmen spenden', 'flynt'),
    'wrapper' => ['width' => 50],
  ],
  [
    'label' => __('Option für Spendenbescheinigung', 'flynt'),
    'name' => 'labelWantsReceipt',
    'type' => 'text',
    'instructions' => __('Text für die Option zur Anforderung einer Spendenbescheinigung, z. B. „Ja, ich möchte eine Jahresspendenbescheinigung“.', 'flynt'),
    'default_value' => __('Ja, ich möchte eine Jahresspendenbescheinigung erhalten.', 'flynt'),
    'wrapper' => ['width' => 100],
  ],
  [
    'label' => __('Hinweis Spendenbescheinigung (Unternehmen)', 'flynt'),
    'name' => 'labelWantsAutoReceipt',
    'type' => 'text',
    'instructions' => __('Hinweistext für automatische Spendenbescheinigung bei Unternehmensspenden.', 'flynt'),
    'default_value' => __('Die Spendenbescheinigung wird automatisch zugeschickt.', 'flynt'),
    'wrapper' => ['width' => 100],
  ],
  [
    'label' => __('Leave No One Behind Newsletter Checkbox Text', 'flynt'),
    'name' => 'labelWantsLNOBNewsletter',
    'type' => 'text',
    'instructions' => __('Text für die Option zur LNOB Newsletter, z. B. „Ich möchte auch von LeaveNoOneBehind Informationen über ihre Arbeit erhalten.“.', 'flynt'),
    'default_value' => __('Ich möchte auch von LeaveNoOneBehind Informationen über ihre Arbeit erhalten.', 'flynt'),
    'wrapper' => ['width' => 100],
  ],
  [
    'label' => __('Feld für Unternehmensname', 'flynt'),
    'name' => 'labelCompanyName',
    'type' => 'text',
    'instructions' => __('Label für das Feld „Unternehmensname“, z. B. „Name des Unternehmens“.', 'flynt'),
    'default_value' => __('Name des Unternehmens', 'flynt'),
    'wrapper' => ['width' => 100],
  ],
  [
    'label' => __('Feld für Straße', 'flynt'),
    'name' => 'labelStreet',
    'type' => 'text',
    'instructions' => __('Label für das Straßenfeld, z. B. „Straße“.', 'flynt'),
    'default_value' => __('Straße', 'flynt'),
    'wrapper' => ['width' => 100],
  ],
  [
    'label' => __('Feld für Hausnummer', 'flynt'),
    'name' => 'labelHouseNumber',
    'type' => 'text',
    'instructions' => __('Label für das Hausnummernfeld, z. B. „Hausnummer“.', 'flynt'),
    'default_value' => __('Hausnummer', 'flynt'),
    'wrapper' => ['width' => 100],
  ],
  [
    'label' => __('Feld für Postleitzahl', 'flynt'),
    'name' => 'labelPostCode',
    'type' => 'text',
    'instructions' => __('Label für das PLZ-Feld, z. B. „Postleitzahl“.', 'flynt'),
    'default_value' => __('Postleitzahl', 'flynt'),
    'wrapper' => ['width' => 100],
  ],
  [
    'label' => __('Feld für Ort', 'flynt'),
    'name' => 'labelCity',
    'type' => 'text',
    'instructions' => __('Label für das Ortsfeld, z. B. „Ort“.', 'flynt'),
    'default_value' => __('Ort', 'flynt'),
    'wrapper' => ['width' => 100],
  ],
  [
    'label' => __('Feld für Land', 'flynt'),
    'name' => 'labelCountry',
    'type' => 'text',
    'instructions' => __('Label für das Länderfeld, z. B. „Land“.', 'flynt'),
    'default_value' => __('Land', 'flynt'),
    'wrapper' => ['width' => 100],
  ],
  [
    'label' => __('Titel für Zahlungsarten-Abschnitt', 'flynt'),
    'name' => 'labelPaymentMethodPanel',
    'type' => 'text',
    'instructions' => __('Überschrift für den Abschnitt zur Auswahl der Zahlungsart, z. B. „Meine Zahlart“.', 'flynt'),
    'default_value' => __('Meine Zahlart', 'flynt'),
    'wrapper' => ['width' => 100],
  ],
  [
    'label' => __('Feld für SEPA-Kontoinhaber', 'flynt'),
    'name' => 'labelBankAccountOwner',
    'type' => 'text',
    'instructions' => __('Label für das Feld „Kontoinhaber“ bei SEPA-Zahlungen, z. B. „Kontoinhaber/-in“.', 'flynt'),
    'default_value' => __('Kontoinhaber/-in', 'flynt'),
    'wrapper' => ['width' => 50],
  ],
  [
    'label' => __('Feld für IBAN', 'flynt'),
    'name' => 'labelBankIban',
    'type' => 'text',
    'instructions' => __('Label für das IBAN-Feld, z. B. „IBAN“.', 'flynt'),
    'default_value' => __('IBAN', 'flynt'),
    'wrapper' => ['width' => 50],
  ],
  [
    'label' => __('Feld für Kreditkarteninhaber', 'flynt'),
    'name' => 'labelCreditCardOwner',
    'type' => 'text',
    'instructions' => __('Label für das Feld „Karteninhaber“ bei Kreditkartenzahlungen, z. B. „Karteninhaber/-in“.', 'flynt'),
    'default_value' => __('Karteninhaber/-in', 'flynt'),
    'wrapper' => ['width' => 50],
  ],
  [
    'label' => __('Feld für Kreditkartennummer', 'flynt'),
    'name' => 'labelCreditCardNumber',
    'type' => 'text',
    'instructions' => __('Label für das Feld „Kartennummer“, z. B. „Kartennummer“.', 'flynt'),
    'default_value' => __('Kartennummer', 'flynt'),
    'wrapper' => ['width' => 50],
  ],
  [
    'label' => __('Feld für Kreditkarten-Gültigkeit', 'flynt'),
    'name' => 'labelCreditCardExpiry',
    'type' => 'text',
    'instructions' => __('Label für das Feld „Gültig bis“ bei Kreditkarten, z. B. „Gültig bis“.', 'flynt'),
    'default_value' => __('Gültig bis', 'flynt'),
    'wrapper' => ['width' => 50],
  ],
  [
    'label' => __('Feld für Kreditkarten-Prüfnummer', 'flynt'),
    'name' => 'labelCreditCardSecureId',
    'type' => 'text',
    'instructions' => __('Label für das Feld „Prüfnummer“ bei Kreditkarten, z. B. „Prüfnummer“.', 'flynt'),
    'default_value' => __('Prüfnummer', 'flynt'),
    'wrapper' => ['width' => 50],
  ],
  [
    'label' => __('Hinweis für Pflichtfelder', 'flynt'),
    'name' => 'mandatoryFields',
    'type' => 'text',
    'instructions' => __('Text, der Pflichtfelder markiert, z. B. „Pflichtfelder“.', 'flynt'),
    'default_value' => __('Pflichtfelder', 'flynt'),
    'wrapper' => ['width' => 50],
  ],
  [
    'label' => __('Hinweistext für PayPal', 'flynt'),
    'name' => 'paypalInfoText',
    'type' => 'wysiwyg',
    'toolbar' => 'basic',
    'media_upload' => 0,
    'instructions' => __('Hinweistext für PayPal-Zahlungen, z. B. Weiterleitung zu PayPal.', 'flynt'),
    'default_value' => __('Klick auf den „Jetzt spenden“-Button. Du wirst automatisch zu PayPal weitergeleitet, wo du deine Spende abschließen kannst.', 'flynt'),
    'wrapper' => ['width' => 100],
  ],
  [
    'label' => __('Hinweistext für Apple Pay', 'flynt'),
    'name' => 'applePayInfoText',
    'type' => 'wysiwyg',
    'toolbar' => 'basic',
    'media_upload' => 0,
    'instructions' => __('Hinweistext für Apple Pay-Zahlungen, z. B. Anweisungen zur Zahlungsfreigabe.', 'flynt'),
    'default_value' => __('Klick auf den „Jetzt spenden“-Button. Die Zahlungsfreigabe erfolgt über Apple Pay. Folge den Anweisungen, um deine Spende abzuschließen.', 'flynt'),
    'wrapper' => ['width' => 100],
  ],
  [
    'label' => __('Hinweistext für Google Pay', 'flynt'),
    'name' => 'googlePayInfoText',
    'type' => 'wysiwyg',
    'toolbar' => 'basic',
    'media_upload' => 0,
    'instructions' => __('Hinweistext für Google Pay-Zahlungen, z. B. Anweisungen zur Zahlungsfreigabe.', 'flynt'),
    'default_value' => __('Klick auf den „Jetzt spenden“-Button. Die Zahlungsfreigabe erfolgt über Google Pay. Folge den Anweisungen, um deine Spende abzuschließen.', 'flynt'),
    'wrapper' => ['width' => 100],
  ],
]);